#!/usr/bin/env python3
"""Generate an audit of static text shown on physical device screens."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "development" / "device-text-audit.md"
SEARCH_DIRS = (
    ROOT / "common" / "setup",
    ROOT / "common" / "device",
    ROOT / "common" / "addon",
    ROOT / "devices",
)
TEXT_RE = re.compile(r"^\s*text:\s*(?P<value>.+?)\s*$")
SKIP_VALUE_RE = re.compile(
    r"^$|^[0-9: /%.-]+$|^https?://|^\$\{?icon_|^\$|^!|^mdi:|^[A-Z0-9_]+$"
)


def yaml_files() -> list[Path]:
    files: list[Path] = []
    for directory in SEARCH_DIRS:
        if directory.is_dir():
            files.extend(
                path
                for path in directory.rglob("*.yaml")
                if ".esphome" not in path.parts and "__pycache__" not in path.parts
            )
    return sorted(files)


def decode_yaml_string(value: str) -> str:
    return bytes(value, "utf-8").decode("unicode_escape")


def parse_text_value(raw: str) -> str:
    raw = strip_yaml_comment(raw).strip()
    if raw.startswith('"') and raw.endswith('"'):
        return decode_yaml_string(raw[1:-1])
    if raw.startswith("'") and raw.endswith("'"):
        return raw[1:-1].replace("''", "'")
    return raw


def strip_yaml_comment(raw: str) -> str:
    in_single = False
    in_double = False
    escaped = False
    for index, char in enumerate(raw):
        if escaped:
            escaped = False
            continue
        if in_double and char == "\\":
            escaped = True
            continue
        if char == '"' and not in_single:
            in_double = not in_double
            continue
        if char == "'" and not in_double:
            in_single = not in_single
            continue
        if char == "#" and not in_single and not in_double:
            return raw[:index]
    return raw


def is_candidate(value: str) -> bool:
    return bool(re.search(r"[A-Za-z]", value)) and not SKIP_VALUE_RE.match(value)


def collect_text() -> dict[str, list[str]]:
    entries: dict[str, list[str]] = defaultdict(list)
    for path in yaml_files():
        relative = path.relative_to(ROOT)
        for line_no, line in enumerate(path.read_text(errors="ignore").splitlines(), 1):
            match = TEXT_RE.match(line)
            if not match:
                continue
            value = parse_text_value(match.group("value"))
            if not is_candidate(value):
                continue
            entries[value].append(f"{relative}:{line_no}")
    return dict(sorted(entries.items(), key=lambda item: item[0].casefold()))


def render_markdown(entries: dict[str, list[str]]) -> str:
    lines = [
        "# Device Text Audit",
        "",
        "Generated by `python3 scripts/audit_device_text.py`.",
        "",
        "This file lists obvious static text literals that can appear on the",
        "physical device display. It is an audit aid for future translation",
        "work; it does not mean every listed value must be translated in the",
        "same way.",
        "",
        "Excluded from this report: empty placeholders, numeric/time values,",
        "icon substitutions, URLs, Home Assistant dynamic values, and lambda",
        "returned text.",
        "",
        f"Candidate strings: {len(entries)}",
        "",
    ]

    for value, locations in entries.items():
        rendered_value = value.replace("\n", "\\n")
        lines.append(f"## {rendered_value}")
        lines.append("")
        lines.append(f"- Locations: {len(locations)}")
        for location in locations:
            lines.append(f"- `{location}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in audit is stale")
    args = parser.parse_args(argv)

    text = render_markdown(collect_text())
    if args.check:
        try:
            current = OUTPUT.read_text()
        except FileNotFoundError:
            print(f"{OUTPUT.relative_to(ROOT)} is missing; run python3 scripts/audit_device_text.py", file=sys.stderr)
            return 1
        if current != text:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run python3 scripts/audit_device_text.py", file=sys.stderr)
            return 1
        print("Device text audit is current.")
        return 0

    OUTPUT.write_text(text)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
